services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=gestion_escolar
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./backend/sql/datos_prueba.sql:/docker-entrypoint-initdb.d/datos_prueba.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    container_name: spring-api
    ports:
      - "8080:8080"
    environment:
      - DB_URI=jdbc:mysql://db:3306/gestion_escolar
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DRIVER=com.mysql.cj.jdbc.Driver

  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend